#!/usr/bin/env bash
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Logging Functions
    consoleColors() {
        NC='\033[0m' # No Color
        R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        INFO='\033[1;37m'
    }
    consoleColors
    
    log_info() {
        echo -e "${B}     INFO┉┐${NC}"
        echo -e "${B}          └┉ ${INFO}$1${NC}"
    }
    ext_info() {
        echo -e "${B}             └┉ ${INFO}$1${NC}"
    }

    log_success() {
        echo -e "${G}  SUCCESS┉┐${NC}"
        echo -e "${G}          └┉ ${INFO}$1${NC}"
    }
    ext_success() {
        echo -e "${G}             └┉ ${INFO}$1${NC}"
    }

    log_warning() {
        echo -e "${Y}  WARNING┉┐${NC}"
        echo -e "${Y}          └┉ ${INFO}$1${NC}"
    }
    ext_warning() {
        echo -e "${Y}             └┉ ${INFO}$1${NC}"
    }

    log_error() {
        echo -e "${R}    ERROR┉┐${NC}"
        echo -e "${R}          └┉ ${INFO}$1${NC}"
    }
    ext_error() {
        echo -e "${R}             └┉ ${INFO}$1${NC}"
    }
#

## Remote Machine 
    DEVICE_INFO_FILENAME="00_DEPLOY_DEVICE_INFO.md"

    USER="$(sed -n '4p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    HOST_NAME="$(sed -n '2p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    INSTALL_TYPE="$(sed -n '6p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    log_info "Username"
    ext_info $USER
    log_info "Hostname"
    ext_info $HOST_NAME
    log_info "Install Environment"
    ext_info $INSTALL_TYPE
    # exit 0

    SSH_LOGIN="${USER}@${HOST_NAME}"

    REMOTE_DIR_HOME="$(ssh "${SSH_LOGIN}" 'echo $HOME')"
    REMOTE_DIR_PGM="${REMOTE_DIR_HOME}/ndpi"
    REMOTE_DIR_PGM_CONFIG="${REMOTE_DIR_PGM}/config"
    REMOTE_DIR_DATA="${REMOTE_DIR_HOME}/DATA_ndpi"
    REMOTE_DIR_TMP="${REMOTE_DIR_HOME}/TMP_ndpi"
##

## GitHub Repo
    REPO_URL="$(head -n 1 ${LOCAL_DIR}/GitHubRepoUrl.txt)"
    BRANCH="$(head -n 1 ${LOCAL_DIR}/version/git)"
##

## Node JS Service Ports
    PORT_API='3080'
    PORT_MDNS='3053'
##

## NDI SDK
    NDI_SDK__NAME="NDI_SDK_v6"
    NDI_SDK__DL_URL="https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_${NDI_SDK__NAME}_Linux.tar.gz"
    NDI_SDK__DL_FILE_NAME="ndi-sdk.tar.gz"
    NDI_SDK__DIR="/opt/NDI SDK for Linux"
    NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/aarch64-rpi4-linux-gnueabi"   # (64-bit) Aarch64 processor Raspberry Pi 4/5
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi1-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 1
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi2-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 2
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi3-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 3
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi4-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 4
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/i686-linux-gnu"               # (32-bit) Intel 6th gen processors (Pentium Pro, Pentium II, Pentium III, Pentium 4)
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/x86_64-linux-gnu"             # (64-bit) Standard AMD/Intel processors
##

# Helper Functions
    getDesktopManager_v1() {
        ssh "${SSH_LOGIN}" \
        "loginctl show-session \$(loginctl | awk '/tty|seat/ {print \$1; exit}') -p Type --value"
    }

    getDesktopManager_v2() {
        ssh "${SSH_LOGIN}" \
        "loginctl list-sessions --no-legend | awk 'NR==1 {print \$1}' | xargs -I{} loginctl show-session {} -p Type --value"
    }

    reboot_wait() {
        local host="${1:-$HOST_NAME}"
        local user="${2:-$USER}"
        local timeout="${3:-180}"
        local interval=3
        local elapsed=0

        echo -e "${Y}          ╰⸺▶ ${INFO}Rebooting Device"

        ssh "${user}@${host}" "sudo reboot"
        sleep 1

        printf  "${B}          ╰⸺▶ ${INFO}Waiting for device online."


        # Phase 1: wait for SSH to accept connections
        while ! ssh -o ConnectTimeout=3 \
                    -o BatchMode=yes \
                    -o StrictHostKeyChecking=no \
                    "${user}@${host}" "exit" 2>/dev/null; do

            printf "."
            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                echo -e "${NC}"
                return 1
            fi
        done

        echo -e "${NC}"

        # Reset timer for next phase
        elapsed=0

        # Phase 2: wait for systemd to report fully running
        while true; do
            state=$(ssh -o ConnectTimeout=3 \
                        -o BatchMode=yes \
                        "${user}@${host}" "systemctl is-system-running" 2>/dev/null)

            if [[ "$state" == "running" ]]; then
                return 0
            fi

            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                log_error "Systemctl not responding"
                ext_error "Last Known State: $state"
                return 1
            fi
        done
    }

    reboot_device() {
        ssh "${SSH_LOGIN}" "sudo reboot"
    }
#

download_ndi_sdk() {
    log_info "Installing NDI SDK"
    sleep 1

    if ! ssh "${SSH_LOGIN}" "
        set -e
        cd /tmp

        echo -e '${INFO}[${NDI_SDK__NAME}]:${NC} Removing Previous NDI SDK Downloads'
        rm -f ${NDI_SDK__DL_FILE_NAME} Install_${NDI_SDK__NAME}_Linux.sh

        echo -e '${INFO}[${NDI_SDK__NAME}]:${NC} Downloading'
        wget -q --show-progress -O ${NDI_SDK__DL_FILE_NAME} '${NDI_SDK__DL_URL}'

        echo -e '${INFO}[${NDI_SDK__NAME}]:${NC} Extracting Downloaded File ${B}(${NDI_SDK__DL_FILE_NAME})${NC}'
        tar -xzf ${NDI_SDK__DL_FILE_NAME}

        echo -e '${INFO}[${NDI_SDK__NAME}]:${NC} Installing'
        chmod +x Install_${NDI_SDK__NAME}_Linux.sh
        yes | sudo ./Install_${NDI_SDK__NAME}_Linux.sh

        echo -e '${INFO}[${NDI_SDK__NAME}]:${NC} Moving to ${B}${NDI_SDK__DIR}${NC}'
        sudo rm -rf '${NDI_SDK__DIR}'
        sudo mv 'NDI SDK for Linux' '${NDI_SDK__DIR}'

        cd '${NDI_SDK__DIR_LIB}'
        sudo cp -P *.* /usr/local/lib
        
        echo -e '${INFO}[${NDI_SDK__NAME}]:${NC} ${G}Installation Complete!${NC}'
    "; then
        log_error "[${NDI_SDK__NAME}]: Download/Install - Failed"
        exit 1
    else
        log_success "${NDI_SDK__NAME} - Installed"
    fi
}

download_ndi_sdk