#!/usr/bin/env bash
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Logging Functions
    consoleColors() {
        NC='\033[0m' # No Color
        R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        INFO='\033[1;37m'
    }
    consoleColors
    
    log_info() {
        echo -e "${B}     INFO┉┐${NC}"
        echo -e "${B}          └┉ ${INFO}$1${NC}"
    }
    ext_info() {
        echo -e "${B}             └┉ ${INFO}$1${NC}"
    }

    log_success() {
        echo -e "${G}  SUCCESS┉┐${NC}"
        echo -e "${G}          └┉ ${INFO}$1${NC}"
    }
    ext_success() {
        echo -e "${G}             └┉ ${INFO}$1${NC}"
    }

    log_warning() {
        echo -e "${Y}  WARNING┉┐${NC}"
        echo -e "${Y}          └┉ ${INFO}$1${NC}"
    }
    ext_warning() {
        echo -e "${Y}             └┉ ${INFO}$1${NC}"
    }

    log_error() {
        echo -e "${R}    ERROR┉┐${NC}"
        echo -e "${R}          └┉ ${INFO}$1${NC}"
    }
    ext_error() {
        echo -e "${R}             └┉ ${INFO}$1${NC}"
    }
#

## Remote Machine 
    DEVICE_INFO_FILENAME="00_DEPLOY_DEVICE_INFO.md"

    USER="$(sed -n '4p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    HOST_NAME="$(sed -n '2p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    INSTALL_TYPE="$(sed -n '6p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    log_info "Username"
    ext_info $USER
    log_info "Hostname"
    ext_info $HOST_NAME
    log_info "Install Environment"
    ext_info $INSTALL_TYPE
    # exit 0

    SSH_LOGIN="${USER}@${HOST_NAME}"

    REMOTE_DIR_HOME="$(ssh "${SSH_LOGIN}" 'echo $HOME')"
    REMOTE_DIR_PGM="${REMOTE_DIR_HOME}/ndpi"
    REMOTE_DIR_PGM_CONFIG="${REMOTE_DIR_PGM}/config"
    REMOTE_DIR_DATA="${REMOTE_DIR_HOME}/DATA_ndpi"
    REMOTE_DIR_TMP="${REMOTE_DIR_HOME}/TMP_ndpi"
##

## GitHub Repo
    REPO_URL="$(head -n 1 ${LOCAL_DIR}/GitHubRepoUrl.txt)"
    BRANCH="$(head -n 1 ${LOCAL_DIR}/version/git)"
##

## Node JS Service Ports
    PORT_API='3080'
    PORT_MDNS='3053'
##

## NDI SDK
    NDI_SDK__NAME="NDI_SDK_v6"
    NDI_SDK__DL_URL="https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_${NDI_SDK__NAME}_Linux.tar.gz"
    NDI_SDK__DL_FILE_NAME="ndi-sdk.tar.gz"
    NDI_SDK__DIR="/opt/NDI SDK for Linux"
    NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/aarch64-rpi4-linux-gnueabi"   # (64-bit) Aarch64 processor Raspberry Pi 4/5
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi1-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 1
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi2-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 2
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi3-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 3
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi4-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 4
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/i686-linux-gnu"               # (32-bit) Intel 6th gen processors (Pentium Pro, Pentium II, Pentium III, Pentium 4)
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/x86_64-linux-gnu"             # (64-bit) Standard AMD/Intel processors
##

# Helper Functions
    getDesktopManager_v1() {
        ssh "${SSH_LOGIN}" \
        "loginctl show-session \$(loginctl | awk '/tty|seat/ {print \$1; exit}') -p Type --value"
    }

    getDesktopManager_v2() {
        ssh "${SSH_LOGIN}" \
        "loginctl list-sessions --no-legend | awk 'NR==1 {print \$1}' | xargs -I{} loginctl show-session {} -p Type --value"
    }

    reboot_wait() {
        local host="${1:-$HOST_NAME}"
        local user="${2:-$USER}"
        local timeout="${3:-180}"
        local interval=3
        local elapsed=0

        echo -e "${Y}          ╰⸺▶ ${INFO}Rebooting Device"

        ssh "${user}@${host}" "sudo reboot"
        sleep 1

        printf  "${B}          ╰⸺▶ ${INFO}Waiting for device online."


        # Phase 1: wait for SSH to accept connections
        while ! ssh -o ConnectTimeout=3 \
                    -o BatchMode=yes \
                    -o StrictHostKeyChecking=no \
                    "${user}@${host}" "exit" 2>/dev/null; do

            printf "."
            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                echo -e "${NC}"
                return 1
            fi
        done

        echo -e "${NC}"

        # Reset timer for next phase
        elapsed=0

        # Phase 2: wait for systemd to report fully running
        while true; do
            state=$(ssh -o ConnectTimeout=3 \
                        -o BatchMode=yes \
                        "${user}@${host}" "systemctl is-system-running" 2>/dev/null)

            if [[ "$state" == "running" ]]; then
                return 0
            fi

            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                log_error "Systemctl not responding"
                ext_error "Last Known State: $state"
                return 1
            fi
        done
    }

    reboot_device() {
        ssh "${SSH_LOGIN}" "sudo reboot"
    }
#

create_program_fs() {
    log_info "Setting up program file system"
    sleep 1

    # Check for Existing Temporary Directory [~/TMP_ndpi]
        if ssh "${SSH_LOGIN}" "[ -d '${REMOTE_DIR_TMP}' ]"; then
            ext_success "TMP directory already exists"
        else
            log_info "Creating TMP directory on device:${NC} ${Y}${REMOTE_DIR_TMP}"
            ext_info "${REMOTE_DIR_TMP}"
            if ! ssh "${SSH_LOGIN}" "
                set -e
                sudo mkdir -p '${REMOTE_DIR_TMP}'
                sudo chown '${USER}':'${USER}' '${REMOTE_DIR_TMP}'
            "; then
                log_error "Failed to create TMP directory on device."
                exit 1
            fi
        fi
    #
    sleep 1

    # Clone Program GitHub Repo into Temporary Directory [~/TMP_ndpi]
        if ssh "${SSH_LOGIN}" "[ -d '${REMOTE_DIR_TMP}/.git' ]"; then
            ext_success "GitHub repo already cloned."
        else
            ext_info "Cloning GitHub repo into TMP"
            ext_info "${REPO_URL}"
            if ! ssh "${SSH_LOGIN}" "
                set -e
                git clone \
                    --branch \
                    '${BRANCH}' \
                    '${REPO_URL}' \
                    '${REMOTE_DIR_TMP}' \
                    &>/dev/null
                sudo chown -R '${USER}':'${USER}' '${REMOTE_DIR_TMP}'
                sudo chmod +x ${REMOTE_DIR_TMP}/sh/*
            "; then
                log_error "Failed to clone repo from GitHub."
                exit 1
            fi
        fi
    #
    sleep 2


    # Check for Existing Program Directory [~/ndpi]
        if ssh "${SSH_LOGIN}" "[ -d '${REMOTE_DIR_PGM}' ]"; then
            ext_success "Program directory already exists."
        else
            log_info "Creating program directory on device:${NC} ${Y}${REMOTE_DIR_PGM}"
            ext_info "${REMOTE_DIR_PGM}"
            if ! ssh "${SSH_LOGIN}" "
                set -e
                sudo mkdir -p '${REMOTE_DIR_PGM}'
                sudo chown '${USER}':'${USER}' '${REMOTE_DIR_PGM}'
            "; then
                log_error "Failed to create program directory on device."
                exit 1
            else
                log_success "Program directory created"
            fi
        fi
    #
    sleep 1

    # Sync Program Directory [~/ndpi] with Temporary Directory [~/TMP_ndpi]
        ext_info "Moving program files from TMP to program directory."
        if ! ssh "${SSH_LOGIN}" "
            set -e
            sudo rsync \
                --archive \
                --itemize-changes \
                --verbose \
                --no-perms \
                --delete \
                --exclude=.git \
                --exclude=.gitignore \
                ${REMOTE_DIR_TMP}/ ${REMOTE_DIR_PGM}
        "; then
            log_error "Failed to transfer program files."
            exit 1
        fi
    #
    sleep 2


    # chmod +x sh/ scripts
        log_info "Applying exec permission to scripts"
        if ! ssh "${SSH_LOGIN}" "
            set -e
            sudo chmod +x ${REMOTE_DIR_PGM}/sh/*
        "; then
            log_error "Failed to apply exec permission to scripts"
            exit 1
        fi
    #

    log_success "Program File System Imported"
}

create_program_fs