#!/usr/bin/env bash
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Logging Functions
    consoleColors() {
        NC='\033[0m' # No Color
        R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        INFO='\033[1;37m'
    }
    consoleColors
    
    log_info() {
        echo -e "${B}     INFO┉┐${NC}"
        echo -e "${B}          └┉ ${INFO}$1${NC}"
    }
    ext_info() {
        echo -e "${B}             └┉ ${INFO}$1${NC}"
    }

    log_success() {
        echo -e "${G}  SUCCESS┉┐${NC}"
        echo -e "${G}          └┉ ${INFO}$1${NC}"
    }
    ext_success() {
        echo -e "${G}             └┉ ${INFO}$1${NC}"
    }

    log_warning() {
        echo -e "${Y}  WARNING┉┐${NC}"
        echo -e "${Y}          └┉ ${INFO}$1${NC}"
    }
    ext_warning() {
        echo -e "${Y}             └┉ ${INFO}$1${NC}"
    }

    log_error() {
        echo -e "${R}    ERROR┉┐${NC}"
        echo -e "${R}          └┉ ${INFO}$1${NC}"
    }
    ext_error() {
        echo -e "${R}             └┉ ${INFO}$1${NC}"
    }
#

## Remote Machine 
    DEVICE_INFO_FILENAME="00_DEPLOY_DEVICE_INFO.md"

    USER="$(sed -n '4p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    HOST_NAME="$(sed -n '2p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    INSTALL_TYPE="$(sed -n '6p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    log_info "Username"
    ext_info $USER
    log_info "Hostname"
    ext_info $HOST_NAME
    log_info "Install Environment"
    ext_info $INSTALL_TYPE
    # exit 0

    SSH_LOGIN="${USER}@${HOST_NAME}"

    REMOTE_DIR_HOME="$(ssh "${SSH_LOGIN}" 'echo $HOME')"
    REMOTE_DIR_PGM="${REMOTE_DIR_HOME}/ndpi"
    REMOTE_DIR_PGM_CONFIG="${REMOTE_DIR_PGM}/config"
    REMOTE_DIR_DATA="${REMOTE_DIR_HOME}/DATA_ndpi"
    REMOTE_DIR_TMP="${REMOTE_DIR_HOME}/TMP_ndpi"
##

## GitHub Repo
    REPO_URL="$(head -n 1 ${LOCAL_DIR}/GitHubRepoUrl.txt)"
    BRANCH="$(head -n 1 ${LOCAL_DIR}/version/git)"
##

## Node JS Service Ports
    PORT_API='3080'
    PORT_MDNS='3053'
##

## NDI SDK
    NDI_SDK__NAME="NDI_SDK_v6"
    NDI_SDK__DL_URL="https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_${NDI_SDK__NAME}_Linux.tar.gz"
    NDI_SDK__DL_FILE_NAME="ndi-sdk.tar.gz"
    NDI_SDK__DIR="/opt/NDI SDK for Linux"
    NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/aarch64-rpi4-linux-gnueabi"   # (64-bit) Aarch64 processor Raspberry Pi 4/5
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi1-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 1
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi2-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 2
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi3-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 3
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi4-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 4
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/i686-linux-gnu"               # (32-bit) Intel 6th gen processors (Pentium Pro, Pentium II, Pentium III, Pentium 4)
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/x86_64-linux-gnu"             # (64-bit) Standard AMD/Intel processors
##

# Helper Functions
    getDesktopManager_v1() {
        ssh "${SSH_LOGIN}" \
        "loginctl show-session \$(loginctl | awk '/tty|seat/ {print \$1; exit}') -p Type --value"
    }

    getDesktopManager_v2() {
        ssh "${SSH_LOGIN}" \
        "loginctl list-sessions --no-legend | awk 'NR==1 {print \$1}' | xargs -I{} loginctl show-session {} -p Type --value"
    }

    reboot_wait() {
        local host="${1:-$HOST_NAME}"
        local user="${2:-$USER}"
        local timeout="${3:-180}"
        local interval=3
        local elapsed=0

        echo -e "${Y}          ╰⸺ ▶ ${INFO}Rebooting Device"

        ssh "${user}@${host}" "sudo reboot"
        sleep 1

        printf  "${B}          ╰⸺ ▶ ${INFO}Waiting for device online."


        # Phase 1: wait for SSH to accept connections
        while ! ssh -o ConnectTimeout=3 \
                    -o BatchMode=yes \
                    -o StrictHostKeyChecking=no \
                    "${user}@${host}" "exit" 2>/dev/null; do

            printf "."
            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                echo -e "${NC}"
                return 1
            fi
        done

        echo -e "${NC}"

        # Reset timer for next phase
        elapsed=0

        # Phase 2: wait for systemd to report fully running
        while true; do
            state=$(ssh -o ConnectTimeout=3 \
                        -o BatchMode=yes \
                        "${user}@${host}" "systemctl is-system-running" 2>/dev/null)

            if [[ "$state" == "running" ]]; then
                return 0
            fi

            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                log_error "Systemctl not responding"
                ext_error "Last Known State: $state"
                return 1
            fi
        done
    }

    reboot_device() {
        ssh "${SSH_LOGIN}" "sudo reboot"
    }
#

config_xinitrc() {
    # xinitrc => Launches openbox
    log_info "Configuring${NC} ${B}.xinitrc"
    ext_info "Copying Config File - xinitrc"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/.xinitrc"
    local CopyToDir="${REMOTE_DIR_HOME}"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File:${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
        sudo chown ${USER}:${USER} ${CopyToDir}/.xinitrc
    "
}

config_openbox() {
    local ConfigFolder="openbox"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    local CopyToDir="${REMOTE_DIR_HOME}${Destination}"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File:${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    if ! ssh "${SSH_LOGIN}" "[ -d '${CopyToDir}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "mkdir -p ${CopyToDir}"
    fi
    
    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
        sudo chown ${USER}:${USER} ${CopyToDir}/${FileName}
        sudo chmod +x ${CopyToDir}/${FileName}
    "

    local FileName="$(sed -n '3p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"

    log_info "Copying Config File - ${FileName}"

    # ext_info "Copying Config File - openbox/rpd-rc"
    # local CopyOf="${REMOTE_DIR_PGM_CONFIG}/openbox/rpd-rc.xml"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File:${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
        sudo chown ${USER}:${USER} ${CopyToDir}/${FileName}
    "
}

config_pcmanfm() {
    local ConfigFolder="pcmanfm"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    local CopyToDir="${REMOTE_DIR_HOME}${Destination}"
    # local CopyToDir="${Destination}"

    # log_info "Configuring${NC} ${B}PCMANFM"
    # ext_info "Copying Config File - pcmanfm"

    # local CopyOf="${REMOTE_DIR_PGM_CONFIG}/pcmanfm/desktop-items-0.conf"
    # local CopyToDir="${REMOTE_DIR_HOME}/.config/pcmanfm/default"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File:${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    if ! ssh "${SSH_LOGIN}" "[ -d '${CopyToDir}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "mkdir -p ${CopyToDir}"
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
    "
}

config_lxpanel() {
    local ConfigFolder="panels"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    local CopyToDir="${REMOTE_DIR_HOME}${Destination}"
    # local CopyToDir="${Destination}"

    # log_info "Configuring${NC} ${B}LXPANEL"
    # ext_info "Copying Config File - lxpanel-pi"

    # local CopyOf="${REMOTE_DIR_PGM_CONFIG}/panels/panel"
    # local CopyToDir="${REMOTE_DIR_HOME}/.config/lxpanel-pi/panels"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File:${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    if ! ssh "${SSH_LOGIN}" "[ -d '${CopyToDir}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "mkdir -p ${CopyToDir}"
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
    "
}

config_unclutter() {
    local ConfigFolder="default"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    # local CopyToDir="${REMOTE_DIR_HOME}${Destination}"
    local CopyToDir="${Destination}"

    # log_info "Configuring${NC} ${B}UNCLUTTER -ROOT"
    # ext_info "Copying Config File - unclutter"

    # local CopyOf="${REMOTE_DIR_PGM_CONFIG}/default/unclutter"
    # local CopyToDir="/etc/default"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File:${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
    "
}

config_autologin() {
    local ConfigFolder="lightdm"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    local CopyToDir="${Destination}"

    # log_info "Configuring${NC} ${B}LIGHTDM"
    # ext_info "Copying Config File - lightdm"

    # local CopyOf="${REMOTE_DIR_PGM_CONFIG}/lightdm/lightdm-autologin.conf"
    # local CopyToDir="/etc/lightdm/lightdm.conf.d"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File:${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    if ! ssh "${SSH_LOGIN}" "[ -d '${CopyToDir}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "sudo mkdir -p ${CopyToDir}"
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
    "
    ssh "${SSH_LOGIN}" "sudo systemctl enable lightdm &>/dev/null"
}

config_chromium() {
    local ConfigFolder="chromium.d"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    local CopyToDir="${Destination}"

    # log_info "Configuring${NC} ${B}CHROMIUM"
    # ext_info "Copying Config File - default-flags"

    # local CopyOf="${REMOTE_DIR_PGM_CONFIG}/chromium.d/default-flags"
    # local CopyToDir="/etc/chromium.d"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    if ! ssh "${SSH_LOGIN}" "[ -d '${CopyToDir}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "sudo mkdir -p ${CopyToDir}"
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
    "
}

config_picom() {
    local ConfigFolder="picom"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    local CopyToDir="${REMOTE_DIR_HOME}${Destination}"
    # local CopyToDir="${Destination}"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    if ! ssh "${SSH_LOGIN}" "[ -d '${CopyToDir}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "sudo mkdir -p ${CopyToDir}"
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
    "
}

config_boot_config() {
    local ConfigFolder="boot_config"
    local FileName="$(sed -n '1p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"
    local Destination="$(sed -n '2p' ${LOCAL_DIR}/config/${ConfigFolder}/00path)"

    log_info "Configuring${NC} ${B}${ConfigFolder}"
    ext_info "Copying Config File - ${FileName}"

    local CopyOf="${REMOTE_DIR_PGM_CONFIG}/${ConfigFolder}/${FileName}"
    # local CopyToDir="${REMOTE_DIR_HOME}${Destination}"
    local CopyToDir="${Destination}"

    if ! ssh "${SSH_LOGIN}" "[ -f '${CopyOf}' ]"; then
        log_error "Config File${NC} ${Y}${CopyOf}${NC} ${R}Does Not Exist"
        return
    fi

    if ! ssh "${SSH_LOGIN}" "[ -d '${CopyToDir}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "sudo mkdir -p ${CopyToDir}"
    fi

    ext_warning "$CopyOf  ⸺ ▶  $CopyToDir/"
    ssh "${SSH_LOGIN}" "
        set -e
        sudo rsync -zq ${CopyOf} ${CopyToDir}/
    "
}


relocate_config_files() {

    log_info "Applying Config..."

    # (6).01 
    # config_xinitrc
    #     sleep 1

    # (6).02 
    config_openbox
        sleep 1

    # (6).03 
    config_pcmanfm
        sleep 1

    # (6).04
    config_lxpanel
        sleep 1

    # (6).05
    config_unclutter
        sleep 1

    # (6).06
    # config_autologin
    #     sleep 1

    # (6).07
    config_chromium
        sleep 1

    # (6).08
    # config_picom
    #     sleep 1

    # (6).09
    config_boot_config

}
relocate_config_files