#!/usr/bin/env bash
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Logging Functions
    consoleColors() {
        NC='\033[0m' # No Color
        R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        INFO='\033[1;37m'
    }
    consoleColors
    
    log_info() {
        echo -e "${B}     INFO┉┐${NC}"
        echo -e "${B}          └┉ ${INFO}$1${NC}"
    }
    ext_info() {
        echo -e "${B}             └┉ ${INFO}$1${NC}"
    }

    log_success() {
        echo -e "${G}  SUCCESS┉┐${NC}"
        echo -e "${G}          └┉ ${INFO}$1${NC}"
    }
    ext_success() {
        echo -e "${G}             └┉ ${INFO}$1${NC}"
    }

    log_warning() {
        echo -e "${Y}  WARNING┉┐${NC}"
        echo -e "${Y}          └┉ ${INFO}$1${NC}"
    }
    ext_warning() {
        echo -e "${Y}             └┉ ${INFO}$1${NC}"
    }

    log_error() {
        echo -e "${R}    ERROR┉┐${NC}"
        echo -e "${R}          └┉ ${INFO}$1${NC}"
    }
    ext_error() {
        echo -e "${R}             └┉ ${INFO}$1${NC}"
    }
#

## Remote Machine 
    DEVICE_INFO_FILENAME="00_DEPLOY_DEVICE_INFO.md"

    USER="$(sed -n '4p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    HOST_NAME="$(sed -n '2p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    INSTALL_TYPE="$(sed -n '6p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    log_info "Username"
    ext_info $USER
    log_info "Hostname"
    ext_info $HOST_NAME
    log_info "Install Environment"
    ext_info $INSTALL_TYPE
    # exit 0

    SSH_LOGIN="${USER}@${HOST_NAME}"

    REMOTE_DIR_HOME="$(ssh "${SSH_LOGIN}" 'echo $HOME')"
    REMOTE_DIR_PGM="${REMOTE_DIR_HOME}/ndpi"
    REMOTE_DIR_PGM_CONFIG="${REMOTE_DIR_PGM}/config"
    REMOTE_DIR_DATA="${REMOTE_DIR_HOME}/DATA_ndpi"
    REMOTE_DIR_TMP="${REMOTE_DIR_HOME}/TMP_ndpi"
##

## GitHub Repo
    REPO_URL="$(head -n 1 ${LOCAL_DIR}/GitHubRepoUrl.txt)"
    BRANCH="$(head -n 1 ${LOCAL_DIR}/version/git)"
##

## Node JS Service Ports
    PORT_API='3080'
    PORT_MDNS='3053'
##

## NDI SDK
    NDI_SDK__NAME="NDI_SDK_v6"
    NDI_SDK__DL_URL="https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_${NDI_SDK__NAME}_Linux.tar.gz"
    NDI_SDK__DL_FILE_NAME="ndi-sdk.tar.gz"
    NDI_SDK__DIR="/opt/NDI SDK for Linux"
    NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/aarch64-rpi4-linux-gnueabi"   # (64-bit) Aarch64 processor Raspberry Pi 4/5
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi1-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 1
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi2-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 2
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi3-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 3
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi4-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 4
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/i686-linux-gnu"               # (32-bit) Intel 6th gen processors (Pentium Pro, Pentium II, Pentium III, Pentium 4)
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/x86_64-linux-gnu"             # (64-bit) Standard AMD/Intel processors
##

# Helper Functions
    getDesktopManager_v1() {
        ssh "${SSH_LOGIN}" \
        "loginctl show-session \$(loginctl | awk '/tty|seat/ {print \$1; exit}') -p Type --value"
    }

    getDesktopManager_v2() {
        ssh "${SSH_LOGIN}" \
        "loginctl list-sessions --no-legend | awk 'NR==1 {print \$1}' | xargs -I{} loginctl show-session {} -p Type --value"
    }

    reboot_wait() {
        local host="${1:-$HOST_NAME}"
        local user="${2:-$USER}"
        local timeout="${3:-180}"
        local interval=3
        local elapsed=0

        echo -e "${Y}          ╰⸺▶ ${INFO}Rebooting Device"

        ssh "${user}@${host}" "sudo reboot"
        sleep 1

        printf  "${B}          ╰⸺▶ ${INFO}Waiting for device online."


        # Phase 1: wait for SSH to accept connections
        while ! ssh -o ConnectTimeout=3 \
                    -o BatchMode=yes \
                    -o StrictHostKeyChecking=no \
                    "${user}@${host}" "exit" 2>/dev/null; do

            printf "."
            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                echo -e "${NC}"
                return 1
            fi
        done

        echo -e "${NC}"

        # Reset timer for next phase
        elapsed=0

        # Phase 2: wait for systemd to report fully running
        while true; do
            state=$(ssh -o ConnectTimeout=3 \
                        -o BatchMode=yes \
                        "${user}@${host}" "systemctl is-system-running" 2>/dev/null)

            if [[ "$state" == "running" ]]; then
                return 0
            fi

            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                log_error "Systemctl not responding"
                ext_error "Last Known State: $state"
                return 1
            fi
        done
    }

    reboot_device() {
        ssh "${SSH_LOGIN}" "sudo reboot"
    }
#

create_env_file() {
    local FILE_PATH="/etc/ndpi"
    local FILE_NAME=".env"

    local LINE_01="PATH=/usr/bin:/usr/local/bin"
    local LINE_02="LD_LIBRARY_PATH=${REMOTE_DIR_PGM}"
    local LINE_03="DISPLAY=:0"
    local LINE_04="TMP_NDPI_PATH=${REMOTE_DIR_TMP}"
    local LINE_05="DATA_NDPI_PATH=${REMOTE_DIR_DATA}"
    local LINE_06="PORT_API=${PORT_API}"
    local LINE_07="PORT_MDNS=${PORT_MDNS}"
    local LINE_08="NODE_ENV=${INSTALL_TYPE}"
    local LINE_09="XAUTHORITY=${REMOTE_DIR_HOME}/.Xauthority"
    local LINE_10="XDG_RUNTIME_DIR=/run/user/1000"
    local LINE_11="OPERATION_STATUS=BUILD"
    local LINE_12=""
    local LINE_13=""
    local LINE_14=""
    local LINE_15=""
    local LINE_16=""
    local LINE_17=""
    local LINE_18=""
    local LINE_19=""
    local LINE_20=""

    local WRITE="sudo tee ${FILE_PATH}/${FILE_NAME}"
    local APPEND="sudo tee -a ${FILE_PATH}/${FILE_NAME}"

    if ! ssh "${SSH_LOGIN}" "[ -d '${FILE_PATH}' ]"; then
        ext_info "Creating Directory..."
        ssh "${SSH_LOGIN}" "sudo mkdir -p ${FILE_PATH}"
    fi

    log_info "Creating File:"
    ext_info "${NC}${B}${FILE_NAME}"
    sleep 1

    if ! ssh "${SSH_LOGIN}" "
        set -e
        echo '${LINE_01}' | ${WRITE}
        echo '${LINE_02}' | ${APPEND}
        echo '${LINE_03}' | ${APPEND}
        echo '${LINE_04}' | ${APPEND}
        echo '${LINE_05}' | ${APPEND}
        echo '${LINE_06}' | ${APPEND}
        echo '${LINE_07}' | ${APPEND}
        echo '${LINE_08}' | ${APPEND}
        echo '${LINE_09}' | ${APPEND}
        echo '${LINE_10}' | ${APPEND}
        echo '${LINE_11}' | ${APPEND}
      # echo '${LINE_12}' | ${APPEND}
      # echo '${LINE_13}' | ${APPEND}
      # echo '${LINE_14}' | ${APPEND}
      # echo '${LINE_15}' | ${APPEND}
      # echo '${LINE_16}' | ${APPEND}
      # echo '${LINE_17}' | ${APPEND}
      # echo '${LINE_18}' | ${APPEND}
      # echo '${LINE_19}' | ${APPEND}
      # echo '${LINE_20}' | ${APPEND}
    "; then
        log_error "Failed to Create: ${FILE_PATH}/${FILE_NAME}"
        exit 1
    fi

    log_success "${NC}${B}${FILE_NAME}${NC}${INFO} - Created"
}
create_env_file