#!/usr/bin/env bash
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Logging Functions
    consoleColors() {
        NC='\033[0m' # No Color
        R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        INFO='\033[1;37m'
    }
    consoleColors
    
    log_info() {
        echo -e "${B}     INFO┉┐${NC}"
        echo -e "${B}          └┉ ${INFO}$1${NC}"
    }
    ext_info() {
        echo -e "${B}             └┉ ${INFO}$1${NC}"
    }

    log_success() {
        echo -e "${G}  SUCCESS┉┐${NC}"
        echo -e "${G}          └┉ ${INFO}$1${NC}"
    }
    ext_success() {
        echo -e "${G}             └┉ ${INFO}$1${NC}"
    }

    log_warning() {
        echo -e "${Y}  WARNING┉┐${NC}"
        echo -e "${Y}          └┉ ${INFO}$1${NC}"
    }
    ext_warning() {
        echo -e "${Y}             └┉ ${INFO}$1${NC}"
    }

    log_error() {
        echo -e "${R}    ERROR┉┐${NC}"
        echo -e "${R}          └┉ ${INFO}$1${NC}"
    }
    ext_error() {
        echo -e "${R}             └┉ ${INFO}$1${NC}"
    }
#

## Remote Machine 
    DEVICE_INFO_FILENAME="00_DEPLOY_DEVICE_INFO.md"

    USER="$(sed -n '4p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    HOST_NAME="$(sed -n '2p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    INSTALL_TYPE="$(sed -n '6p' $(dirname "${BASH_SOURCE[0]}")/$DEVICE_INFO_FILENAME)"
    log_info "Username"
    ext_info $USER
    log_info "Hostname"
    ext_info $HOST_NAME
    log_info "Install Environment"
    ext_info $INSTALL_TYPE
    # exit 0

    SSH_LOGIN="${USER}@${HOST_NAME}"

    REMOTE_DIR_HOME="$(ssh "${SSH_LOGIN}" 'echo $HOME')"
    REMOTE_DIR_PGM="${REMOTE_DIR_HOME}/ndpi"
    REMOTE_DIR_PGM_CONFIG="${REMOTE_DIR_PGM}/config"
    REMOTE_DIR_DATA="${REMOTE_DIR_HOME}/DATA_ndpi"
    REMOTE_DIR_TMP="${REMOTE_DIR_HOME}/TMP_ndpi"
##

## GitHub Repo
    REPO_URL="$(head -n 1 ${LOCAL_DIR}/GitHubRepoUrl.txt)"
    BRANCH="$(head -n 1 ${LOCAL_DIR}/version/git)"
##

## Node JS Service Ports
    PORT_API='3080'
    PORT_MDNS='3053'
##

## NDI SDK
    NDI_SDK__NAME="NDI_SDK_v6"
    NDI_SDK__DL_URL="https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_${NDI_SDK__NAME}_Linux.tar.gz"
    NDI_SDK__DL_FILE_NAME="ndi-sdk.tar.gz"
    NDI_SDK__DIR="/opt/NDI SDK for Linux"
    NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/aarch64-rpi4-linux-gnueabi"   # (64-bit) Aarch64 processor Raspberry Pi 4/5
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi1-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 1
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi2-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 2
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi3-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 3
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/arm-rpi4-linux-gnueabihf"     # (32-bit) ARM processor Raspberry Pi 4
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/i686-linux-gnu"               # (32-bit) Intel 6th gen processors (Pentium Pro, Pentium II, Pentium III, Pentium 4)
    # NDI_SDK__DIR_LIB="${NDI_SDK__DIR}/lib/x86_64-linux-gnu"             # (64-bit) Standard AMD/Intel processors
##

# Helper Functions
    getDesktopManager_v1() {
        ssh "${SSH_LOGIN}" \
        "loginctl show-session \$(loginctl | awk '/tty|seat/ {print \$1; exit}') -p Type --value"
    }

    getDesktopManager_v2() {
        ssh "${SSH_LOGIN}" \
        "loginctl list-sessions --no-legend | awk 'NR==1 {print \$1}' | xargs -I{} loginctl show-session {} -p Type --value"
    }

    reboot_wait() {
        local host="${1:-$HOST_NAME}"
        local user="${2:-$USER}"
        local timeout="${3:-180}"
        local interval=3
        local elapsed=0

        echo -e "${Y}          ╰⸺▶ ${INFO}Rebooting Device"

        ssh "${user}@${host}" "sudo reboot"
        sleep 1

        printf  "${B}          ╰⸺▶ ${INFO}Waiting for device online."


        # Phase 1: wait for SSH to accept connections
        while ! ssh -o ConnectTimeout=3 \
                    -o BatchMode=yes \
                    -o StrictHostKeyChecking=no \
                    "${user}@${host}" "exit" 2>/dev/null; do

            printf "."
            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                echo -e "${NC}"
                return 1
            fi
        done

        echo -e "${NC}"

        # Reset timer for next phase
        elapsed=0

        # Phase 2: wait for systemd to report fully running
        while true; do
            state=$(ssh -o ConnectTimeout=3 \
                        -o BatchMode=yes \
                        "${user}@${host}" "systemctl is-system-running" 2>/dev/null)

            if [[ "$state" == "running" ]]; then
                return 0
            fi

            sleep "$interval"
            ((elapsed+=interval))

            if (( elapsed >= timeout )); then
                log_error "Systemctl not responding"
                ext_error "Last Known State: $state"
                return 1
            fi
        done
    }

    reboot_device() {
        ssh "${SSH_LOGIN}" "sudo reboot"
    }
#

create_node_service_file() {
    local FILE_NAME="ndpi.service"

    local UNIT_01="Description=NDPi Monitor Client - Node Index"    
    local UNIT_02="After=network.target avahi-daemon.service"
    local UNIT_03="Wants=network.target"
    local UNIT_04=""

    local SERVICE_01="Type=simple"
    local SERVICE_02="User=${USER}"
    local SERVICE_03="WorkingDirectory=${REMOTE_DIR_PGM}"
    local SERVICE_04="ExecStartPre=/bin/sleep 1"
    local SERVICE_05="ExecStart=/usr/bin/node ${REMOTE_DIR_PGM}/index.js"
    local SERVICE_06="Restart=always"
    local SERVICE_07="RestartSec=10"
    local SERVICE_08="EnvironmentFile=/etc/ndpi/.env"
    local SERVICE_09=""
    local SERVICE_10=""
    local SERVICE_11=""
    local SERVICE_12=""
    local SERVICE_13=""
    local SERVICE_14=""
    local SERVICE_15=""
    local SERVICE_16=""
    local SERVICE_17=""
    local SERVICE_18=""
    local SERVICE_19=""
    local SERVICE_20=""

    local INSTALL_01="WantedBy=multi-user.target"
    local INSTALL_02=""
    local INSTALL_03=""
    local INSTALL_04=""

    local WRITE="sudo tee /etc/systemd/system/${FILE_NAME}"
    local APPEND="sudo tee -a /etc/systemd/system/${FILE_NAME}"

    log_info "Creating Systemctl Service:"
    ext_info "${NC}${B}${FILE_NAME}"
    sleep 1

    ssh "${SSH_LOGIN}" "
        echo '[Unit]'        | ${WRITE}
        echo '${UNIT_01}'    | ${APPEND}
        echo '${UNIT_02}'    | ${APPEND}
        echo '${UNIT_03}'    | ${APPEND}
      # echo '${UNIT_04}'    | ${APPEND}
        echo ''              | ${APPEND}
        echo '[Service]'     | ${APPEND}
        echo '${SERVICE_01}' | ${APPEND}
        echo '${SERVICE_02}' | ${APPEND}
        echo '${SERVICE_03}' | ${APPEND}
        echo '${SERVICE_04}' | ${APPEND}
        echo '${SERVICE_05}' | ${APPEND}
        echo '${SERVICE_06}' | ${APPEND}
        echo '${SERVICE_07}' | ${APPEND}
        echo '${SERVICE_08}' | ${APPEND}
      # echo '${SERVICE_09}' | ${APPEND}
      # echo '${SERVICE_10}' | ${APPEND}
      # echo '${SERVICE_11}' | ${APPEND}
      # echo '${SERVICE_12}' | ${APPEND}
      # echo '${SERVICE_13}' | ${APPEND}
      # echo '${SERVICE_14}' | ${APPEND}
      # echo '${SERVICE_15}' | ${APPEND}
      # echo '${SERVICE_16}' | ${APPEND}
      # echo '${SERVICE_17}' | ${APPEND}
      # echo '${SERVICE_18}' | ${APPEND}
      # echo '${SERVICE_19}' | ${APPEND}
      # echo '${SERVICE_20}' | ${APPEND}
        echo ''              | ${APPEND}
        echo '[Install]'     | ${APPEND}
        echo '${INSTALL_01}' | ${APPEND}
      # echo '${INSTALL_02}' | ${APPEND}
      # echo '${INSTALL_03}' | ${APPEND}
      # echo '${INSTALL_04}' | ${APPEND}
    "

    ext_info "Reloading Systemctl Daemon"
    ssh "${SSH_LOGIN}" "sudo systemctl daemon-reload"
    ext_info "Enabling -${NC} ${B}${FILE_NAME}"
    ssh "${SSH_LOGIN}" "sudo systemctl enable ${FILE_NAME} &>/dev/null"
    ext_info "Starting -${NC} ${B}${FILE_NAME}"
    ssh "${SSH_LOGIN}" "sudo systemctl restart ${FILE_NAME} &>/dev/null"
    log_success "${NC}${B}${FILE_NAME}${NC}${INFO} - Enabled and Started"
}
create_node_service_file